# Generated by Django 5.0 on 2024-02-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0002_agentbigtimebundleprice_bigtimebundleprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_status',
            field=models.CharField(blank=True, default='Unfinished', max_length=256, null=True),
        ),
    ]
