# Generated by Django 5.0 on 2024-02-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0003_remove_payment_message_payment_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('User', 'User'), ('Agent', 'Agent'), ('Super Agent', 'Super Agent')], max_length=250),
        ),
    ]
