# Generated by Django 4.2.4 on 2024-04-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0007_orderitem_delivered_alter_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='delivered',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='preorder_order_item_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Arrived', 'Arrived')], max_length=250, null=True),
        ),
    ]
