# Generated by Django 4.2.4 on 2024-08-29 12:39

from django.db import migrations, models
import intel_app.custom_storages


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0008_remove_orderitem_delivered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='afaregistration',
            name='occupation',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='afaregistration',
            name='reference',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=intel_app.custom_storages.MediaStorage(), upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=intel_app.custom_storages.MediaStorage(), upload_to='product_images/'),
        ),
    ]
