# Generated by Django 4.2.4 on 2024-08-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0009_announcement_alter_afaregistration_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='ishare_channel',
            field=models.CharField(blank=True, choices=[('Geosams', 'Geosams'), ('Gyasi', 'Gyasi')], max_length=250, null=True),
        ),
    ]
