# Generated by Django 5.2.7 on 2025-11-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0010_admininfo_ishare_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfo',
            name='ishare_channel',
            field=models.CharField(blank=True, choices=[('Geosams', 'Geosams'), ('Gyasi', 'Gyasi'), ('Value4Moni', 'Value4Moni')], default='Geosams', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bigtimetransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='isharebundletransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='mtntransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='mtntransaction',
            name='transaction_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='teleceltransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
