# Generated by Django 5.2.7 on 2025-11-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0011_alter_admininfo_ishare_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='use_paystack_for_topup',
            field=models.BooleanField(default=False),
        ),
    ]
