# Generated by Django 5.2.7 on 2025-11-17 14:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0012_admininfo_use_paystack_for_topup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='topuprequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
